spring:
  profiles: dev

  datasource:
    url: jdbc:h2:file:~/Developer/wiremock_spring/h2/database

wiremock:
  base-path: ~/Developer/wiremock_spring
  file-name: wiremock_spring.jar
  port: 8081

logging:
  level:
    root: DEBUG
    org.springframework.web.reactive.result.method: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
